apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-appset
  namespace: argocd
spec:
  # generator: burada hangi elementlerden application üretileceğini söylüyoruz.
  generators:
    - list:
        elements:
          - name: guestbook
            path: guestbook
            url: https://kubernetes.default.svc
          - name: frontend
            path: frontend
            url: https://kubernetes.default.svc

  # template: her element için oluşturulacak ArgoCD Application şablonu
  template:
    metadata:
      name: '{{name}}'       # element.name ile değişecek (guestbook, frontend)
    spec:
      project: default
      source:
        repoURL: 'https://github.com/your-org/your-repo.git'
        targetRevision: HEAD
        path: '{{path}}'     # element.path ile değişecek
      destination:
        server: '{{url}}'    # element.url ile değişecek
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
