apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helloworld-application-set
spec:
  generators:
    - name: helloworld-app-generator
      clusters:
        - name: cluster-1
          namespace: test
  template:
    metadata:
      name: helloworld-app
    spec:
      project: default
      source:
        repoURL: https://github.com/koraykutanoglu/argocd.git
        path: app
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: test
