apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-hello-world-appset
  namespace: test
spec:
  # See docs for available generators and their specs.
  generators:
  - list:
      elements:
      - cluster: https://kubernetes.default.svc
  template:
    metadata:
      name: test-hello-world-app
    spec:
      project: my-project
      source:
        repoURL: https://github.com/koraykutanoglu/argocd.git
        path: app
        targetRevision: main
      destination:
        server: https://kubernetes.default.svc
        namespace: test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
