apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sample-spring-boot
  namespace: argocd
spec:
  generators:
  - clusters: {} 
  template:
    metadata:
      name: '{{name}}-sample-spring-boot' 
    spec:
      project: default
      source: 
        repoURL: https://github.com/koraykutanoglu/argocd.git
        targetRevision: main
        path: app
      destination:
        server: '{{server}}'
        namespace: demo
      syncPolicy: 
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
