apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-one-product-one
  namespace: test
spec:
  generators:
    list:
    - id: infra
      project: infra-project
    - id: team-two
      project: team-two-project
    template:
      metadata:
        name: test
      spec:
        project: "{{project}}"
