apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-apps
spec:
  generators:
    - git:
        repoURL: git@github.com:example-tenant-apps.git
        revision: HEAD
        files:
          - path: "argocd/tenant-discovery/**/config.json"
  template:
    metadata:
      name: '{{tenant.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/koraykutanoglu/argocd.git
        targetRevision: main
        path: app
      destination:
        server: '{{k8s_cluster.address}}'
        namespace: test
      syncPolicy: { }
