apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  generators:
  - clusters: {} 
  template:
    metadata:
      name: '{{name}}-app' 
    spec:
      project: default
      source: 
        repoURL: https://github.com/koraykutanoglu/argocd.git
        targetRevision: multiple-cluster
        path: agent/templates
      destination:
        server: '{{server}}'
        namespace: demo
      syncPolicy: 
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
