apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: k3s
        url: https://kubernetes.default.svc
      - cluster: k3stwo
        url: https://135.181.98.237:6443
  template:
    metadata:
      name: '{{cluster}}-app' 
    spec:
      project: default
      source: 
        repoURL: https://github.com/koraykutanoglu/argocd.git
        targetRevision: multiple-cluster
        path: agent/templates
      destination:
        server: '{{url}}'
        namespace: demo
      syncPolicy: 
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
