apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-apps
spec:
  destination:
    name: ''
    namespace: test
    server: 'https://kubernetes.default.svc'
  source:
    path: appset
    repoURL: 'https://github.com/koraykutanoglu/argocd.git'
    targetRevision: main
  sources: []
  project: default
